# Generated by Django 3.2.6 on 2021-08-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pc_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='brand_name')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('processor', models.CharField(max_length=50, verbose_name='processor')),
                ('video_card', models.CharField(max_length=50, verbose_name='video_card')),
                ('memory', models.CharField(max_length=50, verbose_name='memory')),
                ('hard_drive', models.CharField(max_length=50, verbose_name='hard_drive')),
                ('height', models.IntegerField(max_length=50, verbose_name='height')),
                ('width', models.IntegerField(max_length=50, verbose_name='width')),
                ('depth', models.IntegerField(max_length=50, verbose_name='depth')),
            ],
            options={
                'verbose_name': 'PC-tables',
                'verbose_name_plural': 'PC-table',
            },
        ),
        migrations.AlterField(
            model_name='laptop',
            name='height',
            field=models.IntegerField(max_length=50, verbose_name='height'),
        ),
    ]
