# Generated by Django 3.2.6 on 2021-08-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20210806_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'verbose_name': 'Mobiles', 'verbose_name_plural': 'Mobile'},
        ),
    ]
