# Generated by Django 3.2.6 on 2021-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_mobile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='img_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='img_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='pc_table',
            name='img_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='pc_table',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
    ]
